<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjH4l1i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjH4l1i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRjH4l1i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRjH4l1i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRjH4l1i\App_KernelDevDebugContainer([
    'container.build_hash' => 'RjH4l1i',
    'container.build_id' => '3fecd83a',
    'container.build_time' => 1635933482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjH4l1i');
