<?php

namespace ContainerXDoopJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YA0PiTIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YA0PiTI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YA0PiTI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminController::delete' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\Admin\\AdminController::editUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\Admin\\AdminOptionController::delete' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController::edit' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController::index' => ['privates', '.service_locator.1piRqeR', 'get_ServiceLocator_1piRqeRService', true],
            'App\\Controller\\Admin\\AdminProduitsController::delete' => ['privates', '.service_locator.arvAwdT', 'get_ServiceLocator_ArvAwdTService', true],
            'App\\Controller\\Admin\\AdminProduitsController::edit' => ['privates', '.service_locator.arvAwdT', 'get_ServiceLocator_ArvAwdTService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.75qYNjo', 'get_ServiceLocator_75qYNjoService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.Vfnlt_K', 'get_ServiceLocator_VfnltKService', true],
            'App\\Controller\\ProduitController::intentSecret' => ['privates', '.service_locator.BYyXXA4', 'get_ServiceLocator_BYyXXA4Service', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.arvAwdT', 'get_ServiceLocator_ArvAwdTService', true],
            'App\\Controller\\ProfilController::editPass' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\ProfilController::history' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Admin\\AdminController:delete' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\Admin\\AdminController:editUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\Admin\\AdminOptionController:delete' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController:edit' => ['privates', '.service_locator.3N8ysha', 'get_ServiceLocator_3N8yshaService', true],
            'App\\Controller\\Admin\\AdminOptionController:index' => ['privates', '.service_locator.1piRqeR', 'get_ServiceLocator_1piRqeRService', true],
            'App\\Controller\\Admin\\AdminProduitsController:delete' => ['privates', '.service_locator.arvAwdT', 'get_ServiceLocator_ArvAwdTService', true],
            'App\\Controller\\Admin\\AdminProduitsController:edit' => ['privates', '.service_locator.arvAwdT', 'get_ServiceLocator_ArvAwdTService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.75qYNjo', 'get_ServiceLocator_75qYNjoService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.Vfnlt_K', 'get_ServiceLocator_VfnltKService', true],
            'App\\Controller\\ProduitController:intentSecret' => ['privates', '.service_locator.BYyXXA4', 'get_ServiceLocator_BYyXXA4Service', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.arvAwdT', 'get_ServiceLocator_ArvAwdTService', true],
            'App\\Controller\\ProfilController:editPass' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\ProfilController:history' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.7AeKCN9', 'get_ServiceLocator_7AeKCN9Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Admin\\AdminController::delete' => '?',
            'App\\Controller\\Admin\\AdminController::editUser' => '?',
            'App\\Controller\\Admin\\AdminOptionController::delete' => '?',
            'App\\Controller\\Admin\\AdminOptionController::edit' => '?',
            'App\\Controller\\Admin\\AdminOptionController::index' => '?',
            'App\\Controller\\Admin\\AdminProduitsController::delete' => '?',
            'App\\Controller\\Admin\\AdminProduitsController::edit' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProduitController::intentSecret' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\ProfilController::editPass' => '?',
            'App\\Controller\\ProfilController::history' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminController:delete' => '?',
            'App\\Controller\\Admin\\AdminController:editUser' => '?',
            'App\\Controller\\Admin\\AdminOptionController:delete' => '?',
            'App\\Controller\\Admin\\AdminOptionController:edit' => '?',
            'App\\Controller\\Admin\\AdminOptionController:index' => '?',
            'App\\Controller\\Admin\\AdminProduitsController:delete' => '?',
            'App\\Controller\\Admin\\AdminProduitsController:edit' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProduitController:intentSecret' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\ProfilController:editPass' => '?',
            'App\\Controller\\ProfilController:history' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
