<?php

namespace ContainerXDoopJA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Option' shared autowired service.
     *
     * @return \App\Entity\Option
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Option.php';

        return $container->privates['App\\Entity\\Option'] = new \App\Entity\Option();
    }
}
