<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6Pv4xx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6Pv4xx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerC6Pv4xx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerC6Pv4xx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerC6Pv4xx\App_KernelProdContainer([
    'container.build_hash' => 'C6Pv4xx',
    'container.build_id' => '3847cb22',
    'container.build_time' => 1635859348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6Pv4xx');
