<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminController::index'], [], [['text', '/admin/']], [], []],
    'admin_utilisateurs' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminController::usersList'], [], [['text', '/admin/utilisateurs']], [], []],
    'admin_modifier_utilisateurs' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminController::editUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/utilisateurs/modifier']], [], []],
    'admin_option_index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminOptionController::index'], [], [['text', '/admin/option/']], [], []],
    'admin_option_new' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminOptionController::new'], [], [['text', '/admin/option/new']], [], []],
    'admin_option_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminOptionController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/option']], [], []],
    'admin_option_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminOptionController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/option']], [], []],
    'admin_produits_index' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminProduitsController::index'], [], [['text', '/admin/produits/index']], [], []],
    'admin_produits_new' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminProduitsController::new'], [], [['text', '/admin/produits/create']], [], []],
    'admin_produits_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminProduitsController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/produits']], [], []],
    'admin_produits_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminProduitsController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/produits/remove']], [], []],
    'order_index' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/order/']], [], []],
    'order_paiement' => [[], ['_controller' => 'App\\Controller\\CartController::ajaxRequest'], [], [['text', '/order/paiement']], [], []],
    'contact_index' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact/']], [], []],
    'indexpage' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'produit' => [[], ['_controller' => 'App\\Controller\\ProduitController::index'], [], [['text', '/carte']], [], []],
    'produit_show' => [['slug', 'id'], ['_controller' => 'App\\Controller\\ProduitController::show'], ['slug' => '[a-z0-9\\-]*'], [['variable', '-', '[^/]++', 'id', true], ['variable', '/', '[a-z0-9\\-]*', 'slug', true], ['text', '/produits']], [], []],
    'profil_index' => [[], ['_controller' => 'App\\Controller\\ProfilController::index'], [], [['text', '/profil/']], [], []],
    'profil_modifier' => [[], ['_controller' => 'App\\Controller\\ProfilController::editProfile'], [], [['text', '/profil/modifier']], [], []],
    'profil_pass' => [[], ['_controller' => 'App\\Controller\\ProfilController::editPass'], [], [['text', '/profil/pass/modifier']], [], []],
    'profil_history' => [[], ['_controller' => 'App\\Controller\\ProfilController::history'], [], [['text', '/profil/history']], [], []],
    'app_inscription' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/inscription']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
