<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_modules_es_objec-0bff99.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ob-907e20.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'menu' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_modules_es_objec-0bff99.js',
                '/build/vendors-node_modules_axios_index_js-node_modules_core-js_modules_es_array_concat_js-node_modu-0cfac1.js',
                '/build/menu.js',
            ],
            'css' => [
                '/build/menu.css',
            ],
        ],
        'user' => [
            'js' => [
                '/build/runtime.js',
                '/build/user.js',
            ],
            'css' => [
                '/build/user.css',
            ],
        ],
    ],
],

]];
