<?php

namespace ContainerKjTZGW0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZE81RhGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZE81RhG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZE81RhG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'produit' => ['privates', 'App\\Entity\\Produits', 'getProduitsService', true],
        ], [
            'produit' => 'App\\Entity\\Produits',
        ]);
    }
}
