<?php

namespace ContainerKjTZGW0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PZXpKPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p_ZXpKP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p_ZXpKP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminController::delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\Admin\\AdminController::editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\Admin\\AdminOptionController::delete' => ['privates', '.service_locator.YCZg.YM', 'get_ServiceLocator_YCZg_YMService', true],
            'App\\Controller\\Admin\\AdminOptionController::edit' => ['privates', '.service_locator.YCZg.YM', 'get_ServiceLocator_YCZg_YMService', true],
            'App\\Controller\\Admin\\AdminOptionController::index' => ['privates', '.service_locator.Kpg3j4e', 'get_ServiceLocator_Kpg3j4eService', true],
            'App\\Controller\\Admin\\AdminProduitsController::delete' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\Admin\\AdminProduitsController::edit' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.XheqsZu', 'get_ServiceLocator_XheqsZuService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.MDxSu07', 'get_ServiceLocator_MDxSu07Service', true],
            'App\\Controller\\ProduitController::intentSecret' => ['privates', '.service_locator.1ZfDXOM', 'get_ServiceLocator_1ZfDXOMService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ProfilController::editPass' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\ProfilController::history' => ['privates', '.service_locator.z4vVS.d', 'get_ServiceLocator_Z4vVS_DService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Admin\\AdminController:delete' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\Admin\\AdminController:editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\Admin\\AdminOptionController:delete' => ['privates', '.service_locator.YCZg.YM', 'get_ServiceLocator_YCZg_YMService', true],
            'App\\Controller\\Admin\\AdminOptionController:edit' => ['privates', '.service_locator.YCZg.YM', 'get_ServiceLocator_YCZg_YMService', true],
            'App\\Controller\\Admin\\AdminOptionController:index' => ['privates', '.service_locator.Kpg3j4e', 'get_ServiceLocator_Kpg3j4eService', true],
            'App\\Controller\\Admin\\AdminProduitsController:delete' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\Admin\\AdminProduitsController:edit' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.XheqsZu', 'get_ServiceLocator_XheqsZuService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.MDxSu07', 'get_ServiceLocator_MDxSu07Service', true],
            'App\\Controller\\ProduitController:intentSecret' => ['privates', '.service_locator.1ZfDXOM', 'get_ServiceLocator_1ZfDXOMService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ProfilController:editPass' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\ProfilController:history' => ['privates', '.service_locator.z4vVS.d', 'get_ServiceLocator_Z4vVS_DService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.wOdllM6', 'get_ServiceLocator_WOdllM6Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Admin\\AdminController::delete' => '?',
            'App\\Controller\\Admin\\AdminController::editUser' => '?',
            'App\\Controller\\Admin\\AdminOptionController::delete' => '?',
            'App\\Controller\\Admin\\AdminOptionController::edit' => '?',
            'App\\Controller\\Admin\\AdminOptionController::index' => '?',
            'App\\Controller\\Admin\\AdminProduitsController::delete' => '?',
            'App\\Controller\\Admin\\AdminProduitsController::edit' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProduitController::intentSecret' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\ProfilController::editPass' => '?',
            'App\\Controller\\ProfilController::history' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AdminController:delete' => '?',
            'App\\Controller\\Admin\\AdminController:editUser' => '?',
            'App\\Controller\\Admin\\AdminOptionController:delete' => '?',
            'App\\Controller\\Admin\\AdminOptionController:edit' => '?',
            'App\\Controller\\Admin\\AdminOptionController:index' => '?',
            'App\\Controller\\Admin\\AdminProduitsController:delete' => '?',
            'App\\Controller\\Admin\\AdminProduitsController:edit' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProduitController:intentSecret' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\ProfilController:editPass' => '?',
            'App\\Controller\\ProfilController:history' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
