<?php

namespace ContainerC6Pv4xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProduitsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\AdminProduitsController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminProduitsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\AdminProduitsController'] = $instance = new \App\Controller\Admin\AdminProduitsController(($container->privates['App\\Repository\\ProduitsRepository'] ?? $container->load('getProduitsRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Admin\\AdminProduitsController', $container));

        return $instance;
    }
}
