<?php

namespace ContainerC6Pv4xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderProduitsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrderProduitsRepository' shared autowired service.
     *
     * @return \App\Repository\OrderProduitsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrderProduitsRepository'] = new \App\Repository\OrderProduitsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
