<?php

namespace ContainerC6Pv4xx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OptionRepository' shared autowired service.
     *
     * @return \App\Repository\OptionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OptionRepository'] = new \App\Repository\OptionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
