<?php

namespace ContainerIBolJ90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminCartControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\AdminCartController' shared autowired service.
     *
     * @return \App\Controller\Admin\AdminCartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/AdminCartController.php';
        include_once \dirname(__DIR__, 4).'/src/Entity/Traits/StripeTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Entity/Order.php';

        $container->services['App\\Controller\\Admin\\AdminCartController'] = $instance = new \App\Controller\Admin\AdminCartController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\OrderRepository'] ?? $container->load('getOrderRepositoryService')), new \App\Entity\Order());

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Controller\\Admin\\AdminCartController', $container));

        return $instance;
    }
}
