<?php

namespace ContainerIBolJ90;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoneyPotTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FormExtension\HoneyPotType' shared autowired service.
     *
     * @return \App\Form\FormExtension\HoneyPotType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormExtension/HoneyPotType.php';

        return $container->privates['App\\Form\\FormExtension\\HoneyPotType'] = new \App\Form\FormExtension\HoneyPotType(($container->services['monolog.logger.honey_pot'] ?? $container->load('getMonolog_Logger_HoneyPotService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
