<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIBolJ90\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIBolJ90/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIBolJ90.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIBolJ90\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIBolJ90\App_KernelDevDebugContainer([
    'container.build_hash' => 'IBolJ90',
    'container.build_id' => '9c38dcf2',
    'container.build_time' => 1674496668,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIBolJ90');
