<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDoopJA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDoopJA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDoopJA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDoopJA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXDoopJA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XDoopJA',
    'container.build_id' => 'df360914',
    'container.build_time' => 1704449534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDoopJA');
