<?php

namespace ContainerIGXHdAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Handler_HoneypotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'monolog.handler.honeypot' shared service.
     *
     * @return \Monolog\Handler\RotatingFileHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php';

        $container->privates['monolog.handler.honeypot'] = $instance = new \Monolog\Handler\RotatingFileHandler((\dirname(__DIR__, 3).'/log/security/honeypot/honeypot.dev.log'), 0, 200, true, NULL, false);

        $instance->pushProcessor(($container->privates['monolog.processor.psr_log_message'] ?? ($container->privates['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor())));
        $instance->setFilenameFormat('{filename}-{date}', 'Y-m-d');

        return $instance;
    }
}
